# Generated by Django 4.2.1 on 2023-05-07 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from pay.utils.gen_pay_data import gen_pay


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='결제 오더 금액')),
                ('status', models.BooleanField(default=False, verbose_name='결제 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='결제 오더 날짜')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='결제 방식')),
            ],
            options={
                'db_table': 'pay',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='결제 지불 금액')),
                ('charge_cost', models.PositiveIntegerField(default=0, verbose_name='선불금 결제 지불 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='결제 날짜')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pay.order')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pay.pay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pay.pay'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='선불금 충전 날짜')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'charge',
            },
        ),
        migrations.RunPython(gen_pay),
    ]
