# Generated by Django 4.2.1 on 2023-05-03 18:16

from django.db import migrations, models

from coupon.utils.gen_coupon_data import gen_coupon


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='쿠폰 이름')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='무료 쿠폰 금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='쿠폰 생성')),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.RunPython(gen_coupon),
    ]
